// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const modalBackground: string;
export const modal: string;
export const playAgainButton: string;
