// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const cell: string;
export const bounce: string;
export const flipGrey: string;
export const flipYellow: string;
export const flipGreen: string;
